require("plugins")
require("config")
require("mappings")
require("set")
require("treesitter")
require("config-alpha") -- alpha startup screen
require("lsp")
require("neotree-config").setup()
require("center-code")
require("statusline")
require("nonels-config")
